#  //////////////////////////////
# //  HYPRARCH CONFIGURATION  //
#//////////////////////////////

### MONITOR  ###
source = ~/.config/hypr/confs/monitors.conf

## AUTOSTART ##
source = ~/.config/hypr/confs/autostart.conf

### CURSOR ###
exec-once = hyprctl setcursor Bibata-Modern-Classic 24 # Set cursor theme and size

### LOOK AND FEEL ###
source = ~/.config/hypr/confs/look_and_feel.conf

### INPUT ###
source = ~/.config/hypr/confs/input.conf

### KEYBINDINGS ###
source = ~/.config/hypr/confs/keybindings.conf

### WINDOWS AND WORKSPACES ###
source = ~/.config/hypr/confs/windows_and_workspaces.conf


