#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 4 # Inner gaps between windows
    gaps_out = 6 # Outer gaps around the screen
    border_size = 2
    col.active_border = rgba(5c76cccc) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    resize_on_border = true
    allow_tearing = false
    layout = dwindle

    no_border_on_floating = true # Disable borders on floating windows
    extend_border_grab_area = 10
}
decoration {
    rounding = 8
    active_opacity = 0.9
    inactive_opacity = 0.8

    shadow {
        enabled = true
        range = 5
        render_power = 4
        color = rgba(00000055)
    }
    blur {
        enabled = true
        size = 5
        passes = 2
	vibrancy = 0.15
        noise = 0.02
    }
}
animations {
    enabled = true
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1
    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 5, winOut, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, loop
    animation = fade, 1, 10, default
    animation = workspaces, 1, 5, wind
}

dwindle {
	pseudotile = true
	preserve_split = true
	split_width_multiplier = 1.1
}
master {
	new_status = master
}
misc {
	force_default_wallpaper = 0
	disable_hyprland_logo = true
}
