##############################
### WINDOWS AND WORKSPACES ###
##############################
# ──────────────────
#   Window Sizes
# ──────────────────
windowrulev2 = size 850 580, class:^(kitty)$
windowrulev2 = size 1000 680, class:^(thunar)$
windowrulev2 = size 1000 700, class:^(yandex-music)$
windowrulev2 = size 850 580, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = size 360 616, class:^(org.gnome.Calculator)$
windowrulev2 = size 950 670, class:^(org.gnome.SystemMonitor)$
windowrulev2 = size 1000 700, class:^(org.telegram.desktop)$
windowrulev2 = size 800 600, class:^(mousepad)$
windowrulev2 = size 1200 800, class:^(com.github.wwmm.easyeffects)$
windowrulev2 = size 700 850, class:^(waypaper)$
windowrulev2 = size 1200 750, class:^(zen)$
windowrulev2 = size 1000 650, class:^(Motrix)$

# ──────────────────────
#   Floating Windows
# ──────────────────────
windowrulev2 = float, class:^(kitty)$
windowrulev2 = float, class:^(thunar)$
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, class:^(yandex-music)$
windowrulev2 = float, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = float, class:^(org.gnome.Calculator)$
windowrulev2 = float, class:^(org.gnome.SystemMonitor)$
windowrulev2 = float, class:^(org.telegram.desktop)$
windowrulev2 = float, class:^(mousepad)$
windowrulev2 = float, class:^(com.github.wwmm.easyeffects)$
windowrulev2 = float, class:^(waypaper)$
windowrulev2 = float, class:^(zen)$
windowrulev2 = float, class:^(Motrix)$

# ──────────────────────────────────────────
#   Window Position / Workspace Placement
# ──────────────────────────────────────────
#windowrulev2 = workspace special:magic, class:^(blueman-manager)$
#windowrulev2 = workspace special:magic, class:^(yandex-music)$
#windowrulev2 = workspace special:magic, class:^(nekoray)$
# Examples:
# windowrulev2 = center, class:.*
# windowrulev2 = move 1600 65, class:^(blueman-manager)$
# ───────────────────────────────────────
#   Prevent idle blocking in fullscreen
# ───────────────────────────────────────
# windowrule = idleinhibit fullscreen, class:([window])
